# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top5_answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('question', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time')),
            ],
        ),
    ]
