# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_questionanswer_socketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='socketid',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
